version: '3.8'

services:
  backend:
    image: openjdk:17-jdk-alpine
    container_name: university-explorer-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/universities?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./target/universities-0.0.1-SNAPSHOT.jar:/app.jar
    entrypoint: [ "sh", "-c", "sleep 20 && java -jar /app.jar" ]
    depends_on:
      - db

  frontend:
    image: node:16-alpine
    container_name: university-explorer-frontend
    build:
      context: ./uniall
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8083
    volumes:
      - ./uniall:/app
    working_dir: /app
    command: [ "sh", "-c", "npm install && npm start" ]

  db:
    image: mysql:8.0
    container_name: university-explorer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universities
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:

